import { SIMULATIONS_LABEL } from "./constants";
export const strings = {
  appName: "주식 길잡이 실험실",
  nav: { lab: "실험실", saved: "저장소", mainMenu: "주 메뉴", menu: "메뉴", bottomTabs: "하단 탭" },
  demoBadge: "데모 · 데이터는 무작위",
  demoBadgeHint: "저장한 실험은 새로고침하면 기본 예시로 돌아가요.",
  theme: { light: "라이트", dark: "다크", system: "시스템 설정" },
  menu: { replayOnboarding: "첫 실험 다시 보기" },
  login: { title: "실험실에 들어가기", enter: "데모로 들어가기" },
  landing: {
    promise: "과거의 하루로 돌아가 그날의 정보만으로 예측하고, 실제 결과와 맞춰봐요.",
    sub: "미래를 맞히는 도구가 아니에요. 예측이 어디서 맞고 틀리는지 과정을 확인하는 실험실이에요.",
    start: "첫 실험 시작하기",
    toLab: "실험실로",
  },
  verdict: { SUCCESS: "예상 성공", FAIL: "예상 실패", PENDING: "채점 전" },
  subjectVerdict: { SUCCESS: "성공", DIRECTION_ONLY: "방향만 맞음", FAIL: "실패", PENDING: "채점 전" },
  toast: { unknownRoute: "찾으시는 화면이 없어 실험실로 이동했어요." },
  lab: {
    emptyResult: "‘계산하기’를 누르면 결과가 나와요.",
    settingsLabel: "설정",
    why: "왜?",
    retry: "다시 시도",
    runFailed: "실행 실패",
    saveFailed: "저장하지 못했어요",
    loading: "계산 중",
    savedToast: (asOf: string) => `저장됨 · ${asOf}`,
    when: {
      title: "언제",
      asOf: "기준 시점",
      today: "오늘",
      weekdaysAgo: (n: number) => `${n}평일 전`,
      dayBefore: "하루 전",
      dayAfter: "하루 뒤",
      horizon: "확인 기간",
      tradingDays: (n: number) => `${n}거래일`,
      run: "계산하기",
      running: "계산 중…",
      save: "저장",
      saved: "저장됨",
      dirty: "바꾼 설정을 먼저 계산해 주세요",
      statusLabel: "설정 상태",
      rerun: "새로 계산",
      viewingSaved: (asOf: string) => `저장한 실험을 보고 있어요 · ${asOf}`,
    },
    whyDescription: {
      summary: `재료를 모아 → ${SIMULATIONS_LABEL}번 굴리고 → 남은 것으로 범위`,
      picks: "그림 읽는 법",
      verdict: "확신도와 채점, 어떻게 나온 숫자인가",
    },
    what: {
      title: "무엇으로",
      expand: "자세히",
      collapse: "접기",
      group: (name: string) => `${name} 재료`,
      layers: { "0": "시장", "1": "업종", "2": "종목" },
      branch: { SHIFT: "방향", WIDTH: "폭", CUT: "체" },
      partial: "일부",
      unavailableFrom: (start: string | null) => `데이터가 ${start ?? "없음"}부터 있어서 이 기준일에는 쓸 수 없어요`,
      notImplemented: "준비 중인 기능이에요",
      cycle: {
        title: "주기",
        hint: "그 기간에 걸린 일정과 계절",
        toggle: "주기 재료",
        off: "끔 · 일정 제외",
        seasonOnly: " · 계절만",
        counting: "일정 세는 중…",
        none: "걸린 일정 없음",
        seasonOn: "계절 켬",
        seasonOff: "계절 끔",
        count: (n: number) => `일정 ${n}건`,
        etc: " 등",
        error: "일정을 불러오지 못했어요.",
        eventsTitle: "업계 시황",
        eventsHint: (asOf: string, horizon: string) => `${asOf} 에 알려져 있던, 앞으로 ${horizon} 안의 일정`,
        eventsCount: (n: number, read: number) => `${n}건 · 방향 읽은 것 ${read}건`,
        eventsEmpty: "이 기간에 등록된 일정이 없어요.",
        columns: ["날짜", "대상", "유형", "무엇", "출처", "알려진 날", "방향", "크기"],
        lateNote: " 기준일 이후 등록 · 예측 제외",
        lateFoot: (n: number) => `흐리게 표시된 ${n}건은 기준일 이후에 나온 일정이에요. 예측 계산에는 들어가지 않았어요.`,
        types: {
          EXPIRY: "만기", RATE: "금리", EARNINGS: "실적", POLICY: "정책", SUPPLY: "공급",
          LEGAL: "소송", MACRO_DATA: "지표", DIVIDEND: "배당락", OTHER: "기타",
        } as Record<string, string>,
        direction: { unknown: "모름", up: "호재", down: "악재", mixed: "갈림" },
      },
      news: {
        title: "뉴스",
        hint: "최근 며칠의 핵심 기사와 판독",
        reading: "기사 읽는 중…",
        error: "뉴스를 불러오지 못했어요.",
        noJudgment: (days: number, total: number) => `${days}일 기사 ${total}건 · 판독 없음`,
        summary: (used: number, market: number, sector: number) => `${used}건 · 시장 ${market} · 업종 ${sector}`,
        header: (asOf: string, days: number, total: number, judged: number) => `${asOf} 앞 ${days}일 · 기사 ${total} · 판독 ${judged}`,
        late: (n: number) => ` (기준일 뒤 ${n})`,
        model: "AI",
        humanOnly: "사람 판독만",
        showUnjudged: (n: number) => `판독 없는 ${n}건 보기`,
        hideUnjudged: "판독 없는 것 숨기기",
        empty: "이 기간에 수집된 기사가 없어요.",
        market: "시장",
        decay: (n: number) => `${n}일`,
        lateFoot: "흐리게 표시된 기사는 기준일 이후에 판독되었어요. 화면에서 참고만 할 수 있고 예측에는 들어가지 않았어요.",
      },
      impact: {
        title: "뉴스 영향",
        hint: "충격이 같았던 날들의 그 뒤",
        toggle: "유사 국면",
        none: "이 환경에는 유사 국면 데이터가 없어요.",
        off: "끔 · 계산 제외",
        groups: { news: "뉴스", width: "폭", cut: "체" },
      },
    },
    summary: {
      title: "계산",
      sectors: "업종 ",
      count: (n: number) => `${n}개`,
      of: " 중 ",
      picked: "를 뽑아 1등 종목으로 ",
      after: " 뒤 ",
      expected: "를 예상했다. ",
      notYet: (horizon: string) => `아직 ${horizon}이 지나지 않아 실제 결과가 나오지 않았어요.`,
      actual: "실제는 ",
      partial: "확인 기간이 진행 중이에요. 지금까지는 ",
      bench: ", 같은 기간 시장은 ",
      vsMarket: " — 시장보다 ",
      earnedMore: "더 벌었어요",
      earnedLess: "덜 벌었어요",
      cost: " (왕복 거래비용 ",
      costTail: "를 뺀 값)",
      noneLead: "를 뽑았다 — 전부 시장보다 못할 것 같거나, 내릴 것 같다. 시장은 ",
      noneTail: "로 봤다.",
    },
    picks: {
      title: "무엇을 뽑았나",
      header: (asOf: string, horizon: string, samples: number) => `${asOf} 기준 · ${horizon} · 표본 길 ${samples}/${SIMULATIONS_LABEL}`,
      layer: "층",
      layerSector: (n: number) => `시장 · 업종 ${n}`,
      layerLeader: (n: number) => `시장 · 1등 종목 ${n}`,
      mode: "무엇을 그리나",
      modeActual: "실제 움직임",
      rankLabel: "업종 순위",
      base: "기준선",
      inRange: "범위 ✓",
      outRange: "범위 ✗",
      guess: "예상",
      chartLabel: "경로 차트",
    },
    verdict: {
      title: "맞았나",
      columns: {
        sector: "업종",
        leader: "1등 종목",
        flow: "예상 흐름",
        flowHint: (horizon: string) => `${horizon} · 음영 80%`,
        tri: "상승 · 횡보 · 하락",
        expected: "예상",
        actual: (horizon: string) => `${horizon} 뒤 실제`,
        verdict: "판정",
        pick: "선정",
      },
      market: "시장",
      kospi: "코스피",
      detail: (name: string) => `${name} 자세히`,
      pushed: "무엇이 밀었나",
      pick: { base: "기준", belowStart: "내릴 듯", filtered: "걸림" },
      tri: (up: number, flat: number, down: number) => `상승 ${up}% · 횡보 ${flat}% · 하락 ${down}%`,
      footer: (n: number) => `뽑은 업종 ${n}개 평균`,
      hits: (dir: number, range: number, total: number) => `방향 ${dir}/${total} · 범위 ${range}/${total}`,
    },
    guide: {
      title: "첫 실험",
      skip: "건너뛰기",
      why: "왜 이렇게 하나요?",
      terms: "처음 나온 말",
      stepDone: "완료",
      progress: (n: number) => `${n}/4`,
      viewResult: "결과 확인하기",
      steps: [
        {
          name: "언제로 갈까",
          head: "예측하는 날과 채점하는 날이 달라요",
          body: "기준 시점은 예측을 시작하는 날이고, 확인 기간은 실제 결과를 확인할 때까지의 기간이에요. 왼쪽에서 기준 시점을 옮기거나 확인 기간을 바꿔 보세요.",
        },
        {
          name: "무엇을 볼까",
          head: "그날까지 알 수 있던 정보만 써요",
          body: "미래 데이터는 미리 보지 않아요. 기준 시점 전에 알려진 일정과 뉴스, 유사 국면 데이터만 모아요. 왼쪽에서 재료를 펼쳐 어떤 정보가 들어가는지 확인해 보세요.",
        },
        {
          name: "자동 계산",
          head: `${SIMULATIONS_LABEL}번 시뮬레이션해 범위를 계산해요`,
          body: `모은 재료로 앞날을 ${SIMULATIONS_LABEL}번 시뮬레이션해 보고, 유효한 경로를 추려 예상 범위와 중앙값을 계산해요. 날짜나 재료를 바꾸면 자동으로 다시 계산돼요.`,
        },
        {
          name: "결과 읽기",
          head: "예상과 실제, 판정 결과를 확인해요",
          body: "선정한 업종과 예상 수익률, 경로 차트, 실제 결과와의 비교 판정을 한눈에 볼 수 있어요. 아래 판정 표까지 스크롤해 보세요.",
        },
      ],
    },
  },
  saved: {
    title: "저장소",
    empty: "실험실에서 저장을 누르면 여기에 모여요.",
    toLab: "실험실로",
    open: "실험실에서 열기",
    tradingDays: "거래일",
    savedAt: "저장",
    modules: (n: number) => `켠 재료 ${n}개`,
    picked: "뽑은 업종",
    nonePicked: "없음",
    card: (asOf: string) => `${asOf} 실험`,
    loadFailed: "저장한 실험을 불러오지 못했어요.",
  },
} as const;
