// 원본 번들에서 데모 생성기 구간을 잘라 ESM 모듈로 만든다.
// 구간: 설정 상수 `Jv=!0,Yv=` 부터 요청 분기 객체 `wy={...}` 의 닫는 중괄호까지.
// 구간이 밖에서 쓰는 식별자는 API 오류 클래스 `Nd` 하나뿐이라 앞에 붙인다.
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const bundle = resolve(here, "../../shin-yxy-mock/assets/index-DpGc5H-z.js");
const out = resolve(here, "../src/demo/generated/adapter.js");

const START = "Jv=!0,Yv=";
const END = "},Ty;(function(e){e.Unimplemented";

const js = readFileSync(bundle, "utf8");
const s = js.indexOf(START);
if (s < 0) throw new Error(`start marker not found: ${START}`);
const e = js.indexOf(END, s);
if (e < 0) throw new Error(`end marker not found: ${END}`);
const region = js.slice(s, e + 1);

const header = [
  "// GENERATED by scripts/extract-demo.mjs from shin-yxy-mock/assets/index-DpGc5H-z.js.",
  "// Do not edit. Re-run `pnpm extract` instead.",
  "/* eslint-disable */",
  "class Nd extends Error{status;detail;errors;problem;constructor(e,t,n){super(t),this.name=`ApiError`,this.status=e,this.detail=n?.detail,this.errors=n?.errors,this.problem=n?.problem}get isNetworkError(){return this.status===0}}",
  "var ",
].join("\n");

const footer =
  ";\nexport { Nd as ApiError, ty as config, dy as runLab, gy as events, yy as news, by as demoUser, Xv as sectors, Zv as tickers, $v as Rng, Qv as hashSeed, Cy as rawRequest };\n";

mkdirSync(dirname(out), { recursive: true });
writeFileSync(out, header + region + footer);
console.log(`wrote ${out} (${region.length} bytes of bundle)`);
